import Head from 'next/head'
import Link from 'next/link'
import {useState} from "react"
import  Axios  from 'axios';
import endPoint from "../components/endPoint"
import Loader from '../components/loader';
export default function Home() {
  const [email , setemail] = useState("")
    const [password , setpassword] = useState("")
    const [loader, setloader] = useState(false)
  const handleLogin = ()=>{
    if(email && password){
      setloader(true)
      Axios.post(endPoint + "/login" , {email : email , password:password})
      .then(doc=>{
        new Promise((resolve, reject) => {
          resolve()
          localStorage.setItem("user" , JSON.stringify(doc.data.staff))
          localStorage.setItem("token" , JSON.stringify(doc.data.token))
        }).then(()=>window.location.assign("account"))
      }).catch(err=>{
        if(err.message === "Request failed with status code 422"){
          alert("Wrong credentials")
        }else{
        alert(err.message)
        setloader(false)
        }
      
      })
    }else{
      alert("Make sure to enter your email and password")
     }
  }
  return (
    <div>
      <Head>
        <title>Hr Management</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {
        loader ?
        <Loader />
        :""
      }

      <div className="">
        <div className="central loginLeft gradient">
          <img src="/connect.svg" className='fit' alt="" />
        </div>
        <div className="loginRight central">
        <div className="form">
          <div className="h1 p-text">
            GSS HR MANAGEMENT SYSTEM 
          </div>
        <div className='m-section'>
          <div className="h1">Login Account</div>
          <div className='text-bold'>
          Enter a valid email and password to login your account
         </div>
         </div>
         <p>
          <input type="email" name="" className='input' id="" placeholder='EMAIL' onChange={(e)=>setemail(e.target.value)}/>
         </p>
         <p>
          <input type="password" name="" className='input' id="" placeholder='PASSWORD' onChange={(e)=>setpassword(e.target.value)}/>
         </p>
         <p>
         <button className="primaryBtn btn full-width" onClick={handleLogin}>LOGIN ACCOUNT</button>
         </p>
        </div>
        </div>
      </div>

    </div>
  )
}
